### ISSUE TITLE
Increasing Login Time

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#170]
Current cookie time is a bit short and seems to expire too fast. We could allow user to set cookie duration or change the time logged in to a bit longer interval.

https://github.com/DakuTree/manga-tracker/blob/master/application/config/ion_auth.php#L95

**Comment by DakuTree** [comment]
15360355b4fee08dc7963f1e6855849a7ca9104d added an option on the login page which allows the user to set their own expire time.

**Comment by Vesnyx** [comment]
@DakuTree Does the login time work for you? I still get logged out super early, seems like about 2~3 hours before getting locked out. When I check the cookies, the only ones that expire fast are the ci_session and the csrf token. I might try in a different browser, but I don't think the cookies are getting reset by any of my extensions since they're all disabled on the site.

**Comment by DakuTree** [comment]
Should be fixed as of the above commit.

Seems like Ion Auth was re-generating the `identity` & `remember_code` cookies when the `ci_session` cookie expired, which meant the expiry time was being reset to the default time.

**Comment by Vesnyx** [comment]
Still doesn't appear to be working, other than how there's one more cookie for remember_time.

**Comment by DakuTree** [comment]
Not too sure what could have caused that. Both cookies are setting the expiry properly on my end, as well as when `ci_session` expires.

Had you re-logged since the above commit?

**Comment by Vesnyx** [comment]
I re-logged, but I still keep getting logged out. The cookie's property's look fine to me as the 'identity', 'remember_time' and 'remember_code' have their expiration dates properly set. The thing is, I had set the expiration date to November when the custom time was first set up, which is why they all expire around November 17th and 19th. However, everytime it forced me to re-log, I would leave the login time at 3 days, but the cookies never got changed. I'll check what's expired before I'm forced to login next time, because I really can't figure out what's causing this.

**Comment by DakuTree** [comment]
Is this issue still occurring?

**Comment by Vesnyx** [comment]
Yeah, I'm still getting logged out after 3 hours. I have no idea what's causing this. I'll try another browser since my extensions might be interfering with it.

**Comment by Vesnyx** [comment]
After some preliminary testing, it seems like it was indeed some of my extensions causing the problems. I'll have to manually check each one to see what the problem is, but I believe the issue as a whole can be closed so I'll close the issue for now,
