### ISSUE TITLE
Series not being updated properly?

### ISSUE THREAD

**Issue by DakuTree** [DakuTree/manga-tracker#223]
From bug report:
> Massive list of 'series that have been marked inactive'.
> The box containing this has stayed here for a while.`

Actually had this a few times myself but it was usually resolved by a manual update.

Not sure what exactly is happening here, as the manual update always fixes it.

**Comment by Vesnyx** [comment]
Oh this is mine. Occasionally, I'll get a giant list with a bunch of series that it says have been marked inactive and will be updated. I've checked around the ones I've gotten, and it usually seems like 1 series has been DMCA'd (bato.to). In the bug report I submitted, Gabriel Dropout had all its chapters removed when I got this message, but there was a rather large list of series that were listed in the yellow box, many of which were completely fine in terms of updating; this includes things that update daily like Mousou Telepathy.

**Comment by Vesnyx** [comment]
To add on to this, the yellow box never actually disappears for me after a refresh. It seems like until the series are manually updated, it'll stay in the user's dashboard.

**Comment by DakuTree** [comment]
This is fixed as per the above commit (bca6495839f3c8d1d7127272f6f779d9743ed0de).

**Comment by Vesnyx** [comment]
Getting this error a bunch still. This has been here for a good couple of days. Also, there are a few LHtranslation series that don't seem to have been updated properly. ![untitled](https://user-images.githubusercontent.com/4986454/32417832-0d4d8f88-c214-11e7-93db-796080277580.png)

**Comment by Vesnyx** [comment]
@DakuTree Still getting this issue with the same series as well. There's also a few series that say they've marked/ignored but they still work on LHTranslation. Tomodachi Game from batoto also experiencing this issue.

**Comment by DakuTree** [comment]
Should be fixed now. Title wasn't being grabbed properly which was causing everything else to fail..

**Comment by Vesnyx** [comment]
@DakuTree Might be slightly related but for certain series:

Tomodachi Game on Batoto
Murenase! Shiiton Gakuen on Batoto
Magi Craft Meister on LHTranslation

I get the "This title is no longer being updated as it has been marked as deleted/ignored." error message. These series have had this "error" message on them for awhile now, so I was wondering if they were mismarked. I know that all 3 of these series actually got "taken down"-ish from their respective sites, resulting in a series of errors, but they've been reuploaded.

**Comment by DakuTree** [comment]
Have went and re-enabled updating for them. Will be an hour or so before they grab the new chapters though.

**Comment by Vesnyx** [comment]
@DakuTree 
Still a few more series on LHTranslation that aren't getting updated. Additionally, it seems like certain series don't have their names properly parsed. 

> Ibitsu no Amalgam

 gets registered as 

> Ib

 for some reason. 

> Hiraheishi wa Kako o Yumemiru

 gets cutoff at the Y and looks like 

> Hiraheishi wa Kako o Y

There's a few more series that have issues like that, so I guess the parser isn't properly pulling the title.

Anywho, here's the series that weren't getting updated properly:
Isekai Goumon Hime
Grancrest Senki

**Comment by DakuTree** [comment]
@Vesnyx Looks like the regex was removing too much from the title. Should be fixed now.

> Anywho, here's the series that weren't getting updated properly:
Isekai Goumon Hime
Grancrest Senki

Had to disable these manually after they changed the site since they didn't have a chapter page. Should start updating now.
