### ISSUE TITLE
ReadMangaToday domain swap

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#233]
They may be changing their domain to 
http://www.readmng.com/
as that's where the old URL redirects to.

**Comment by Vesnyx** [comment]
Icon CSS still needs to be fixed and updates still appear to be failing.

**Comment by DakuTree** [comment]
Icon CSS shouldn't need changed since we're just passing the old domain when updating since it's easier.
Update issues should be fixed now.

**Comment by Vesnyx** [comment]
I meant the hover on icon text. It still shows readmanga.today. The search is broken for it as well. Searching `site:www.readmanga.today` pulls up the manga on www.readmng.com.
