### ISSUE TITLE
MAL Sync not setting chapter properly

### ISSUE THREAD

**Issue by cublikefoot** [DakuTree/manga-tracker#320]
## Bug report

**What is the bug?**
When marking a chapter as latest read (from the chapter page itself) on some manga, it is synced to MAL incorrectly, syncing the latest available chapter rather than the chapter just read.

It seems to be syncing the chapter just read, then immediately overwriting it with the latest available. See this image (from my MAL history): http://puu.sh/zpRZn/5b141ab0bf.png

**Please provide steps to reproduce:**
I have had this happen with a few manga now, but it can be easily reproduced using MangaStream's reader for "The Promised Neverland". Just mark any chapter that is not the latest as the last chapter read using the red book icon at the top of the page (with MAL syncing set up of course).

I have also noticed a visual issue with MangaStream that may be related? http://puu.sh/zpS4W/6eb8f273ba.png
Refreshing the page here causes it to display properly (as c050), but immediately after syncing from the chapter page (and before refreshing trackr.moe) it displays the chapter number along with some of the MangaStream URL trailing it.

**Comment by DakuTree** [comment]
Both issues should be fixed as per the above two commits. Might need to update the userscript manually to get the fixes asap.

**Comment by cublikefoot** [comment]
Issue still seems to be there, only when dashboard is open while updating from chapter on another tab. When dashboard is closed it updates correctly though.

**Comment by DakuTree** [comment]
Pushed another fix for this which seems to solve the issue.
